### PR TITLE
Carlos

### PR DESCRIPTION
**Pull request by Carlos-Nisum**

### CODE REVIEW

**Comment by Carlos-Nisum** [comment]
Fixed some more css stuff and wrote some more code for the api calls for the previous orders page. This branch also contains changes made from pull request titled, "added nav bar comps to every page plus user var in ts files #18 " (please merge that before merging this request).

**Review by emiliobatan — COMMENTED** [review]
Looks good to go, just make sure to merge Patricks pull request before this one

**Review by patastic4 — APPROVED** [review]
new changes to previous-orders

**Review by GottaGitGoing — APPROVED** [review]
I like the service classes you wrote!

**Review by Andrew-Nisum — APPROVED** [review]

**Pull request merged**
